INSERT INTO teams (userId, fullName, alias) VALUES (2, 'Meltdown 6', 'Meltdown 6');
INSERT INTO teams (userId, fullName, alias) VALUES (3, 'Arstotzkaasschaaf', 'Arstotzkaasschaaf');
INSERT INTO teams (userId, fullName, alias) VALUES (4, 'CatalonIA', 'CatalonIA');
INSERT INTO teams (userId, fullName, alias) VALUES (5, 'Sealand', 'Sealand');
INSERT INTO teams (userId, fullName, alias) VALUES (6, 'U.S.S.Arrrrr', 'U.S.S.Arrrrr');
INSERT INTO teams (userId, fullName, alias) VALUES (7, 'Schmutzig - K*****gezwellig', 'Schmutzig');
INSERT INTO teams (userId, fullName, alias) VALUES (8, 'Abusement World', 'Abusement World');
INSERT INTO teams (userId, fullName, alias) VALUES (9, 'San Quentin', 'San Quentin');
INSERT INTO teams (userId, fullName, alias) VALUES (10, 'Carpe Noctem', 'Carpe Noctem');
INSERT INTO teams (userId, fullName, alias) VALUES (11, 'Vaulting Roast Mobsters', 'Roast Mobsters');
INSERT INTO teams (userId, fullName, alias) VALUES (13, 'Easteros', 'Easteros');
INSERT INTO teams (userId, fullName, alias) VALUES (14, 'Radio-/Actief/', 'Radio-Actief');
INSERT INTO teams (userId, fullName, alias) VALUES (15, 'The Kingdom of New Nippal', 'New Nippal');
INSERT INTO teams (userId, fullName, alias) VALUES (16, 'Teringtubbieland', 'Teringtubbieland');
INSERT INTO teams (userId, fullName, alias) VALUES (17, 'Sherlockington', 'Sherlockington');
INSERT INTO teams (userId, fullName, alias) VALUES (18, 'Brakfrika', 'Brakfrika');
INSERT INTO teams (userId, fullName, alias) VALUES (19, 'Kapitalipsum', 'Kapitalipsum');
INSERT INTO teams (userId, fullName, alias) VALUES (20, 'West Korea', 'West Korea');
INSERT INTO teams (userId, fullName, alias) VALUES (21, 'Assgard', 'Assgard');
INSERT INTO teams (userId, fullName, alias) VALUES (22, 'Democratic Peoples Republic of IAPC', 'DPR of IAPC');
INSERT INTO teams (userId, fullName, alias) VALUES (23, 'Wasteland Survivor&#x27;s Guide to the Post-Apocalypse', 'Survivors Guide');
INSERT INTO teams (userId, fullName, alias) VALUES (24, 'Rainbow mutations', 'Rainbow mutations');
INSERT INTO teams (userId, fullName, alias) VALUES (25, 'Tegijl', 'Tegijl');
INSERT INTO teams (userId, fullName, alias) VALUES (26, 'Team UnBEETable', 'Team UnBEETable');
INSERT INTO teams (userId, fullName, alias) VALUES (27, 'Black beads of the yellow sun', 'Black beads');
INSERT INTO teams (userId, fullName, alias) VALUES (28, 'Disneyland', 'Disneyland');